### ISSUE TITLE
Armor Graphic Bug

### ISSUE THREAD

**Issue by RotokEralil** [Skylortrexler/MegaParrot#1]
Hello! When putting armor on the MP's without a saddle, they have missing textures (I assume theres no image for them without a saddle to pull).
Not something gamebreaking, but something I noticed when I put the armor on before I put the saddle.
(and  would love a way to add custom horse armor, or support for other mods horse armor, but not sure if there is a way without having to manually create images for them all).

**Comment by skylorbeck** [comment]
Can you screenshot what you mean by missing textures?

**Comment by RotokEralil** [comment]
> Can you screenshot what you mean by missing textures?
[https://imgur.com/a/VDUmTh5](https://imgur.com/a/VDUmTh5)
Once I reloaded the world, I could only repeat the graphic error with custom horse armors (placing vanilla armor in first worked fine. )
So I have no idea now how to repeat (didnt screenshot first time).

**Comment by skylorbeck** [comment]
Woah. That's super weird. I tested it without saddles and the saddle is actually inside the regular texture. Thanks for the report. I'll look into it and see what the cause might be. On Jan 3, 2022 9:53 PM, RotokEralil ***@***.***> wrote:

Can you screenshot what you mean by missing textures?
https://imgur.com/a/VDUmTh5
Once I reloaded the world, I could only repeat the graphic error with custom horse armors (placing vanilla armor in first worked fine. )
So I have no idea now how to repeat (didnt screenshot first time).
