### ISSUE TITLE
No data fixer registered for megaparrot:megaparrot

### ISSUE THREAD

**Issue by purejosh** [Skylortrexler/MegaParrot#10]
[22:02:52] [main/ERROR]: No data fixer registered for megaparrot:megaparrot

Minecraft 1.19.2 with Fabric Loader 0.14.9
megaparrot 1.0.5

**Comment by skylorbeck** [comment]
Not a bug, also causes no harm aside from one red line at boot

**Comment by purejosh** [comment]
Is it too much to ask to have the error addressed?

**Comment by skylorbeck** [comment]
Yes because there is no bug and there is no harm. Please research datafixers to understand why. They are not as relevant to mods as they are to vanilla.
