### ISSUE TITLE
[Compat Suggestion] Origins

### ISSUE THREAD

**Issue by CasualJeremy** [Skylortrexler/MegaParrot#11]
Not sure if you take these sorts of suggestions but I figured I'd give it a shot. Also heads up, your Discord link is invalid.

Similarly to the MythicMounts mod, it would be cool if you could stunt the growth of the Mega Parrot as a Mega Baby Parrot so Origins like the Inchling (Extra Origins) or Moth (Mo's Grounded Origins) could use them.

**Comment by skylorbeck** [comment]
Sorry for the late reply, Can you please tell me which discord link you used? I deleted ones that had a high volume of spam traffic and it's hard to track down where they were posted.

**Comment by CasualJeremy** [comment]
The link in CurseForge for Discord is invalid

I figure my request would be difficult but i am curious as to what you think of it?

**Comment by skylorbeck** [comment]
Well, currently the Baby Mega Parrot is actually just a Parrot so I'm not sure how that would work.
