### ISSUE TITLE
[Bug] Pehkui mod - Rider position issue

### ISSUE THREAD

**Issue by SylisMC** [Skylortrexler/MegaParrot#12]
megaparrot-1.0.7-1.19.2.jar
Pehkui-3.4.2+1.14.4-1.19.2.jar

When the scale of the bird is changed, the rider doesn't sit in the right position
![2022-10-05_22 22 11](https://user-images.githubusercontent.com/19602662/194200087-d30191c9-6a2f-42d6-8249-5a5e161535f7.png)

**Comment by skylorbeck** [comment]
Yeah that makes sense. Pehkui changes a lot with how the game works. I don't have the time to add compatibility for it.
