### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheButterbrotMan** [Skylortrexler/MegaParrot#2]
https://pastebin.com/6udv25Hx

**Comment by skylorbeck** [comment]
Can you give me some more info? What were you doing at the time of crash?

**Comment by TheButterbrotMan** [comment]
Sorry, cant reproduce the crash. It just happens multiple times a day.

**Comment by skylorbeck** [comment]
But what are you doing when it crashes. I can't do anything about it if I can't replicate it. It has something to do with holding the food. You have so many mods that I have to assume one of them edits something related to food or horses.

**Comment by TheButterbrotMan** [comment]
Probably i would say exploring. Theres no mod that edit horses. Additional theres alot of food mods.
