### ISSUE TITLE
Sorry but

### ISSUE THREAD

**Issue by dumpyman** [Skylortrexler/MegaParrot#7]
I understand that this is starting to get annoying, but I will just say that
mega parrots wont spawn(naturally). I can summon them with /summon but I don't know how to explain to server members that I used cheats
I have these mods:
appleskin-fabric-mc1.18.2-2.4.0
architectury-4.4.56
campanion-3.0.3
caracal-1.18.2-1.3.8
charm-fabric-1.18-4.1.0
cloth-config-6.2.62-fabric
Clumps-fabric-1.18.2-8.0.0+8
collective-fabric-1.18.x-4.26
ecologics-FABRIC-1.18.2-1.5.4
elytraboosters-1.3.0
fabric-api-0.51.1+1.18.2
fabric-language-kotlin-1.7.4+kotlin.1.6.21
friendsandfoes-fabric-mc1.18.2-1.3.4
geckolib-fabric-1.18-3.0.42
geckolib-quilt-1.18-3.0.6
go-fish-1.5.0-1.18.2
ironfurnaces-1.18-3.0.0-fabric
justplayerheads-fabric_1.18.x-1.8
magehand-1.1.2
megaparrot-1.0.5
mobscarecrow-1.2.2
pickyourpoison-1.0.5
ratsmischief-1.3.7
skylorlib-1.3.34

**Comment by skylorbeck** [comment]
I can't explain that to them for you. Without any errors I have to assume there is no bug and it is user error. Please check your configs and settings for the server.

**Comment by dumpyman** [comment]
I didn't edit the config or the server settings

**Comment by skylorbeck** [comment]
I didn't say you did. Check them.
